import { prisma } from '../../prisma/client.js';

/**
 * Fetches the configured minimum watch duration from the settings table.
 * Falls back to 30 seconds if the setting is missing or invalid.
 */
async function getMinViewDuration() {
  const setting = await prisma.setting.findUnique({
    where: { key: 'min_view_duration_seconds' },
  });
  const parsed = parseInt(setting?.value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 30;
}

/**
 * Records a qualified view for a show.
 *
 * Rules (per FRD):
 * - watch_duration_sec must meet the configured threshold.
 * - (session_id, show_id) is unique — duplicate calls within the same session
 *   are silently ignored (idempotent).
 * - On success, increments show.view_count (organic counter) by 1.
 *
 * @param {object} params
 * @param {string} params.showId
 * @param {string} params.sessionId   - UUID v4 generated by the mobile client at playback start
 * @param {string|null} params.userId - null for non-logged-in (device-only) sessions
 * @param {string|null} params.episodeId
 * @param {number} params.watchDurationSec - cumulative active playback time (not seek position)
 *
 * @returns {{ counted: boolean, reason: string }}
 *   counted: true  → new view was recorded
 *   counted: false → duplicate session or below threshold
 */
async function recordView({ showId, sessionId, userId, episodeId, watchDurationSec }) {
  const minDuration = await getMinViewDuration();

  // Guard: below threshold — client should not have fired, but defend server-side too
  if (watchDurationSec < minDuration) {
    return { counted: false, reason: 'below_threshold' };
  }

  // Attempt to insert the audit row. The unique index on (session_id, show_id)
  // will reject a duplicate without us needing a separate SELECT first.
  try {
    await prisma.$transaction(async (tx) => {
      // Insert audit row — throws on duplicate (unique constraint violation)
      await tx.viewCountEvent.create({
        data: {
          session_id: sessionId,
          show_id: showId,
          episode_id: episodeId ?? null,
          user_id: userId ?? null,
          watch_duration_sec: Math.floor(watchDurationSec),
          source: 'organic',
        },
      });

      // Increment the organic counter only if insert succeeded
      await tx.show.update({
        where: { id: showId },
        data: { view_count: { increment: 1 } },
      });
    });

    return { counted: true, reason: 'recorded' };
  } catch (err) {
    // P2002 = Prisma unique constraint violation → duplicate session, ignore silently
    if (err?.code === 'P2002') {
      return { counted: false, reason: 'duplicate_session' };
    }
    // Any other DB error — re-throw so the route can handle it
    throw err;
  }
}

/**
 * Computes the publicly displayed view count for a show.
 * displayed = organic view_count + manual_view_count
 *
 * @param {{ view_count: number, manual_view_count: number }} show
 * @returns {number}
 */
function displayedViewCount(show) {
  return (show.view_count ?? 0) + (show.manual_view_count ?? 0);
}

export { recordView, displayedViewCount, getMinViewDuration };